### ISSUE TITLE
Consider decomposing the project

### ISSUE THREAD

**Issue by DamienCassou** [emacs-elsa/Elsa#108]
I have the impression that Elsa is doing several things: it can annotate an AST with type information and it can use this information and other information to report defects. To me, this seems like 2 different packages. For example, I could write a refactoring tool that would use the type annotations to drive the refactorings. In this case, it would bother me to make the refactoring tool depend on a linter.

**Comment by Fuco1** [comment]
There is a task for this already #17.  I prefer monorepo to many packages
