### ISSUE TITLE
Function = can take markers as argument

### ISSUE THREAD

**Issue by DamienCassou** [emacs-elsa/Elsa#115]
```emacs
(= (point) (point-marker))
```

Elsa complains:

> Argument 2 accepts type Number but received Marker

This is wrong because `=` accepts `Marker` as argument. Above expression should answer `t`.

**Comment by DamienCassou** [comment]
I see a TODO in elsa-typed-builtin.el:

```
;; TODO: should also accept markers
(put '= 'elsa-type (elsa-make-type Number -> Number... -> Bool))
```

if you tell me how to change that to accept markers, I could help you do the change.

**Comment by Fuco1** [comment]
@DamienCassou Heh, I think it's currently impossible to express actually :D

Maybe `Number | Marker -> Variadic (Number | Marker) -> Bool` or something like that could work.  Once we finish #74 the syntax will be better.
