### ISSUE TITLE
Update "How do I run it" in README

### ISSUE THREAD

**Issue by Fuco1** [emacs-elsa/Elsa#135]
Elsa is now on MELPA so that should be the default channel.

- update the Cask instructions (should still be default)
- expand the flycheck section (how to install, what to setup in Emacs)
- mention emake.el (@vermiculus can you write a short paragraph on how to run it?)
- mention how to run it "DIY style" (not recommended)

**Comment by vermiculus** [comment]
Here's what I would say for EMake:

> Install [EMake](https://github.com/vermiculus/emake.el) via the usual means (`curl -fsSL https://raw.githubusercontent.com/vermiculus/emake.el/master/new | sh`). You can now run Elsa's checks with `make lint-elsa`.

**Comment by Fuco1** [comment]
@vermiculus thanks, that is simpler than I expected :D

**Comment by vermiculus** [comment]
😉
