### ISSUE TITLE
Hard time installation on Windows x64

### ISSUE THREAD

**Issue by randomwangran** [emacs-elsa/Elsa#138]
I try to run elsa on a windows x64 machine. Not sure it was
tested yet. If running it on Linux is a must, I would like to
try. But, in case someone has already play with elsa in Windows. I
just log something that I've encountered.

<a id="org5862e60"></a>

#### git clone <https://github.com/emacs-elsa/Elsa.git> somewhere to your computer.

I've download elsa via `git clone`.

The latest commit: `78273ac`.

<a id="org65f5a4a"></a>

#### Add (depends-on "elsa") to Cask file of your project

I've created a new folder called: `elsaTest`, which contains two
files:
```
-rw-rw-rw-  1 user None    643 01-24 21:06 Cask
-rw-rw-rw-  1 user None   4.9k 01-17 09:53 elsa.el
```

In the `Cask` file:

```elisp
(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "elsa")
```

The `elsa.el` is the exactly same file I clone from:
`https://github.com/emacs-elsa/Elsa.git`

<a id="org8c38350"></a>

#### Run cask link elsa <path-to-elsa-repo>

1.  open the program: `C:\Windows\system32\cmd.exe`
2.  go to the path: `C:\Windows\user\Documents\rep\Elsa>_`
3.  type the command: `cask link elsa .`

<a id="org761c947"></a>

#### cask exec elsa <file-to-analyse> to analyse the file. Currently only one file at a time can be analysed.

1.  change the path to: `C:\Users\user\Documents\rep\elsaTest>`
2.  show the content of this directory:
    `C:\Users\user\Documents\rep\elsaTest>ls`
    `Cask elsa.el`
3.  type the command: `C:\Users\user\Documents\rep\elsaTest>cask exec elsa elsa.el`

```
cask exec: error: Failed to execute elsa elsa.el: (2, 'No such file or directory
')
Did you run cask install?
```

1.  type command: `C:\Users\user\Documents\rep\elsaTest>cask
             install`
    then, a bunch of things shown in the `cmd.exe`

2.  type command: `C:\Users\user\Documents\rep\Elsa>cask link
             elsa .`
3.  type command: `C:\Users\user\Documents\rep\elsaTest>cask exec elsa elsa.el`

```
cask exec: error: Failed to execute elsa elsa.el: (2, 'No such file or directory
')
Did you run cask install?
```

<a id="org3a74b43"></a>

#### to illustrate the installation of cask I did this:

```
C:\Users\user\Documents\rep\cask>cask version

C:\Users\user\Documents\rep\cask>0.8.4
```

**Comment by Fuco1** [comment]
You don't need to `cask link` anymore since Elsa can now be installed from MELPA archive directly.  I will need to update the installation instructions.

The problem here is probably `cask link elsa .`.  The dot needs to point to the repository you've cloned.

Windows is currently not officially supported platform but it might work, you're the first person giving back feedback, so we'll see how far we can get.

**Comment by Fuco1** [comment]
Elsa should work on windows using Eask, possibly even Cask.  I'm going to close this issue since 2019 is long time ago and Cask and Elsa had many releases inbetween.
