### ISSUE TITLE
A likely typo

### ISSUE THREAD

**Issue by xuchunyang** [emacs-elsa/Elsa#141]
https://github.com/emacs-elsa/Elsa/blob/65cd51c183d0ae57cd22d0b623727519c2644d87/elsa-typed-builtin.el#L128-L129

The only DEFUN in the file is `(byte-code BYTESTR VECTOR MAXDEPTH)`.

**Comment by Fuco1** [comment]
OOOOHHH :D So this is why I was getting those super-funny warnings on `eq` comparisons about "vector mixed"... Thanks for catching it!  I was going to spend some quality time checking the `eq` extension which I've added some time ago.

This saved me couple hours easily :)

**Comment by Fuco1** [comment]
@xuchunyang Do you want to craete a pull request?  Changing the `eq` to the function you mentioned should be enough.  You deserve your commit counter to go up! :D

**Comment by xuchunyang** [comment]
I've created a pull request.
