### ISSUE TITLE
There is already an open source project called Elsa: https://github.com/dsw/oink-stack/tree/master/elsa

### ISSUE THREAD

**Issue by dsw** [emacs-elsa/Elsa#158]
There is already an open source project called Elsa: https://github.com/dsw/oink-stack/tree/master/elsa

It is customary to not re-use names of open source projects.  For example, when Netscape was reborn as open-source, it was first named Phoenix, then Firebird, and then Firefox: https://en.wikipedia.org/wiki/Firefox

"The Firefox project has undergone several name changes.[40][41][42][43][44][45][46][47] The nascent browser was originally named Phoenix, after the mythical bird that rose triumphantly from the ashes of its dead predecessor (in this case, from the "ashes" of Netscape Navigator, after was sidelined by Microsoft Internet Explorer in the "First Browser War"). Phoenix was renamed due to a trademark claim from Phoenix Technologies. The replacement name, Firebird, provoked an intense response from the Firebird database software project.[48][49] The Mozilla Foundation reassured them that the browser would always bear the name Mozilla Firebird to avoid confusion. After further pressure, Mozilla Firebird became Mozilla Firefox on February 9, 2004.[50] The name Firefox was said to be derived from a nickname of the red panda,[51] which became the mascot for the newly named project.[52]"

**Comment by Fuco1** [comment]
I replied to the email but for completeness I will copy the answer here.

> Hi Daniel.
> The projects are in two very unrelated domains and the chance of confusion is minimal.  I won't be renaming the project.
> Regards, Matus.
