### ISSUE TITLE
Unable to analyse

### ISSUE THREAD

**Issue by contrapunctus-1** [emacs-elsa/Elsa#165]
As mentioned in [#159](https://github.com/emacs-elsa/Elsa/issues/159#issuecomment-530947513), running `cask exec elsa chronometrist.el` returns -

> Other must be ‘elsa-type-child-p’

I haven't added an Elsafile.el yet, FWIW.

[Permalink to file](https://framagit.org/contrapunctus/chronometrist/blob/9e9b165558fd2d5b05bfd82f13d6151ed22e5c1b/chronometrist.el)

**Comment by Fuco1** [comment]
@contrapunctus-1 I think that's the problem, I've added it.

I need to rework the startup so it defaults to something reasonable, see also #153

**Comment by contrapunctus-1** [comment]
I've added an Elsafile.el containing the following to the project root (same directory as the Cask file) -

```
(register-extensions dash cl elsa)

(register-ruleset dead-code style error variables elsa)
```

and I still run into the issue :\

**Comment by contrapunctus-1** [comment]
Ah, I forgot to run `cask update`. Now (with Elsa v20191002.2030) and the Elsafile.el above, I'm able to analyze the file.
