### ISSUE TITLE
[Question] How to handle cl-defstructs from other, require'd packages?

### ISSUE THREAD

**Issue by nbfalcon** [emacs-elsa/Elsa#173]
In my project I require flycheck and make use of one of its types: flycheck-error. It is defined with cl-defstruct. When I specify a type signature making use of it (as per the readme, just specifying the struct name) as '(flycheck-projectile-buffer-errors :: Buffer -> [flycheck-error])', I get an error: Unknown type flycheck-error.

Can Elsa follow requires, or is there some way to define types for elsa explicitly?

**Comment by Fuco1** [comment]
There is now support for defstruct and defclass, both create a type `(struct NAME)`.  The support for defclass is currently better as cl-defstruct does not include inheritance yet.
