### ISSUE TITLE
Elsa crashes on reading `'(x . y)` syntax

### ISSUE THREAD

**Issue by ethan-leba** [emacs-elsa/Elsa#176]
### Steps to reproduce

1. Make a file with the following contents:
```
'(foo . foo)
```
2. Run `cask exec elsa bug.el`.

3. Receive the following error:
```
Wrong type argument: listp, #s(elsa-form-symbol 9 12 nil 1 8 #s(elsa-type-mixed) nil #s(trinary 1) unbound ...)
```

Not sure if this syntax is explicitly not supported by elsa or something. `(cons 'foo 'foo)` works fine, but I'm using the `.` syntax for pattern matching, which makes `cons` inconvenient.

Thanks for this cool plugin! (is this still alive?)

**Comment by Fuco1** [comment]
All the valid syntax is supported so this should also work.

The project is currently hibernating, but I still want to get back to it eventually, if only for the intellectual fun of it.

**Comment by ethan-leba** [comment]
The issue appears to be due to an upstream change with `dash.el` -- I've opened a small PR if you have time to take a look 👍

**Comment by Fuco1** [comment]
Yes, this is due to dash.el indeed... I've just spent some time debugging it when you already did the work :man_facepalming:  I even did the same change than you did to fix it.  I'll revert my changes and merge your code in recognition of your help and my futility.  Thanks!
