### ISSUE TITLE
Build fails because it installs some old version of Elsa from melpa?

### ISSUE THREAD

**Issue by Fuco1** [emacs-elsa/Elsa#202]
@jcs090218 is the `eask install` step necessary for testing?

https://github.com/emacs-elsa/Elsa/actions/runs/4245952892/jobs/7382137790

**Comment by jcs090218** [comment]
This is what these steps do:

```yaml
eask package  # Build installable artifect
eask install      # Install that artifect (the local version of Elsa)
```

I don't think it fails because of the old version of Elsa, it must be the version on the master branch. The error only tells you, "you got this error while your users trying to install this package".

**Comment by Fuco1** [comment]
OK, I wasn't sure if it was downloading from MELPA.

There was some problem with incorrect requires (circular dependency I forgot to delete), so I guess now it works.  False alarm, sorry :blush:
