### ISSUE TITLE
Use without Eask or Cask ?

### ISSUE THREAD

**Issue by mmontone** [emacs-elsa/Elsa#222]
Hello,

I think it would be great to be able to use this without having to install Eask or Cask.

Just install from Melpa, then run a command for initializing/caching, and use.

I see the packages are there, but doesn't run without Eask or Cask.

Would that be possible?

**Comment by Fuco1** [comment]
You can use makem or emake which do not require cask or eask but use makefiles or shell scripts.

Currently it's not possible to run Elsa from the host session, it must run in a separate Emacs process.
