### ISSUE TITLE
Add types for all built-in types

### ISSUE THREAD

**Issue by Fuco1** [emacs-elsa/Elsa#31]
For naming use the [type predicates](https://www.gnu.org/software/emacs/manual/html_node/elisp/Type-Predicates.html#Type-Predicates) and follow the convention.

- [ ] [Programming types](https://www.gnu.org/software/emacs/manual/html_node/elisp/Programming-Types.html#Programming-Types)
- [ ] [Editing types](https://www.gnu.org/software/emacs/manual/html_node/elisp/Editing-Types.html#Editing-Types)

**Comment by DamienCassou** [comment]
Fixed in #118?
