### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by Fuco1** [emacs-elsa/Elsa#80]
I've created an organization https://github.com/emacs-elsa and we need a logo for the project.

**Comment by wasamasa** [comment]
Too bad I never learned to use Illustrator or Inkscape, only Photoshop.

The name reminds me of the German word "Elster", the magpie. How about a sideways portrait shot showing off its black and white feathers?

**Comment by nashamri** [comment]
Just to brainstorm some ideas, I'm not sure if the name "Elsa" is just simply an abbreviation of "Emacs Lisp Static Analyzer" or @Fuco1 meant something specific :smile:. What came to my mind when I first saw the name of the project is the Disney character Elsa from Frozen (Yeah I have a little daughter :laughing:).

![](https://media.giphy.com/media/vtgyj63bjCWvS/giphy.gif)

And since we are talking about *static* analysis of types, there might be some commonalities between the words **Static** and **Frozen**. So, maybe something that represents **freezing** could be a logo? like a snowflake or an ice cube or an iceberg?

I'm not sure if the connection between that character and this project is a cool (no pun intended) idea or it's a bit childish. Anyways, I'm just throwing ideas out there :smile:

**Comment by Fuco1** [comment]
@nashamri If you look into the readme you can find this:

![](https://i.imgur.com/LzFsDMB.png)

So yea, there was a bit of a double-meaning :D But it was effortless pun.

**Comment by Fuco1** [comment]
@nashamri I think the snowflake/ice idea is pretty *solid* (yea, we should stop with the puns :D).  I think the leap from static to frozen is not that far indeed.

**Comment by nashamri** [comment]
@Fuco1 :laughing: that's cool! I might try to sketch some ideas then, and post them here when I'm done :wink:

**Comment by alphapapa** [comment]
One "cheap" idea (in terms of difficulty) would be to take the Emacs icon and replace the "E" with a snowflake.

**Comment by nashamri** [comment]
Okay, I've created several logos and I'm not sure which one is the best. So, here you go:
![elsa-logos](https://user-images.githubusercontent.com/1207107/44616514-f7568b80-a859-11e8-8240-84e1a93c8f9a.png)
The colors are not final, this is just for the shape design. Also, regarding the word "ELSA" I'm not sure if we should put it in the logo or not.

Bonus:
Little video of me sketching out some ideas before actually doing the logo in inkscape.

![elsa](https://user-images.githubusercontent.com/1207107/44616588-16095200-a85b-11e8-9e10-9efae5d747c3.gif)

**Comment by Fuco1** [comment]
@nashamri Wow, sweet!  That's a lot of work, thanks a lot!

The color scheme reminds me a bit of https://nixos.org/ which is an OS based on purely functional package manager.  I wonder if they got similar idea.  I think we would be pushing it too far if we made the "rays" into lambdas though :D

That video looks like pure magic to me. That's not done by hand right?  The middle design and the one on top-right are boss as hell.

From the first set I like number 9, 2 is also pretty similar. The two-color variants look a bit more "fun" to me than the single-color designs.

I would avoid putting in the name, if for anything than for legal reasons, I don't want to get shut down by Disney lol.

**Comment by nashamri** [comment]
@Fuco1 Thanks! :smile:

Yeah it dose look like nixos logo, I'm wondering too if the idea behind the snowflake in their logo is similar to what we had in mind :thinking:

The video was done by hand using an iPad and an app called procreate. The app has a lot of brushes and tools to make your strokes symmetrical. So, I was drawing a single line and that line will be duplicated 5 more times to create that hexagonal shape of the snowflake. The app exports bitmaps and not vector based graphics. So, I won't be able to use any of these in the final logo (unless I trace these bitmaps). Anyhow, it was meant to be an *exploratory* study of the shape.

I like no. 9 too and I think it's well-balanced. I'll play with some colors and post back :smile:

**Comment by alphapapa** [comment]
Very nice work.  In the last set, 8, 9, and 11 stand out to me.  

* I wonder how 8 would look with its white lines having a bit of embellishment like 9's.  I like 8's embellishments between the white lines.
* I wonder how 9 would look with its white lines reduced in width, length, and/or brightness a little--IOW, de-emphasized slightly.
* 11 kind of feels like something is missing, since it doesn't have the white lines, but at the same time it is interesting and perhaps slightly understated, which is also nice.

Just some ideas, feel free to ignore.  :)

**Comment by Fuco1** [comment]
I like 2, 3 and 6 with 3 being probably my fav.  The "full" design (8-11) doesn't appeal to me, I like the rays sticking out.

**Comment by nashamri** [comment]
Hey @alphapapa here are more attempts :smile: 

> I wonder how 8 would look with its white lines having a bit of embellishment like 9's. I like 8's embellishments between the white lines.
![1](https://user-images.githubusercontent.com/1207107/44618839-4a463800-a886-11e8-8910-b91cec727edf.png)

> I wonder how 9 would look with its white lines reduced in width, length, and/or brightness a little--IOW, de-emphasized slightly.
![2](https://user-images.githubusercontent.com/1207107/44618846-68ac3380-a886-11e8-9056-15ad786d4329.png)

> 11 kind of feels like something is missing, since it doesn't have the white lines, but at the same time it is interesting and perhaps slightly understated, which is also nice.
![3](https://user-images.githubusercontent.com/1207107/44618855-795ca980-a886-11e8-89bb-27a8d6f7175b.png)

> It would be interesting to see a few of them in the Emacs icon color theme, just for fun. I'm just trying to brainstorm a way to visually tie them in to Emacs, if that's possible.

Yeah good idea will do more color studies once we find the design of the logo :smile: 

Here is another one:
![4](https://user-images.githubusercontent.com/1207107/44618868-b9bc2780-a886-11e8-98f4-5ae7087977e8.png)

**Comment by nashamri** [comment]
> I like 2, 3 and 6 with 3 being probably my fav. The "full" design (8-11) doesn't appeal to me, I like the rays sticking out.

Yeah I think we got carried away a bit :smile: I like how simple and representative the design of the shapes 1..6

**Comment by alphapapa** [comment]
They all look great!

**Comment by nashamri** [comment]
All righty, we are getting there, all that is left is the colors now :smile: 
![elsa-logos-3](https://user-images.githubusercontent.com/1207107/44621062-46c3a880-a8a8-11e8-9c9d-c49282ed5175.png)
The purple is to link it to emacs as @alphapapa suggested.

**Comment by alphapapa** [comment]
Those look great in purple too!

**Comment by Fuco1** [comment]
Yea, I like 2 and 3 as well, 4 and 5 feel a bit bleached out, 6 is also good but I feel like the dark outline works better.

I think purple is fine indeed, I also like 1 but I think the purple design makes more sense.  So for me it's between 2 and 3.

**Comment by alphapapa** [comment]
> So for me it's between 2 and 3.

I would vote for 3.

**Comment by nashamri** [comment]
I like no. 3 the best. It looks like no. 3 got the most praise. So, do we have a winner? :smile: 
@Fuco1 Should I create a repo for the logo like this one https://github.com/nashamri/spacemacs-logo, or do you prefer another way?

**Comment by nashamri** [comment]
@Fuco1 here you go https://github.com/nashamri/elsa-logo I really don't don't mind moving this to the project or doing whatever you like. Thank you and all you guys for improving the ecosystem of emacs :+1: keep up the good work!

**Comment by Fuco1** [comment]
@nashamri when I put the logo to the org https://github.com/emacs-elsa there are some subtle bars on top and bottom (png version), is that intentional?

**Comment by nashamri** [comment]
Oh, that's the border of the background and it's not intentional :) I'll
fix that in a bit.

**Comment by alphapapa** [comment]
I guess the background should be transparent, too.  I'm using a user stylesheet for GitHub, which doesn't have a white background, and the logo's white background shows up as a white square against the page.

**Comment by nashamri** [comment]
@Fuco1 This https://github.com/nashamri/elsa-logo/commit/1aeeb9888f0950c5a35502b785cb09516e358fa5 removes the border from the PNG and (@alphapapa) I've added another PNG with no background.

**Comment by Fuco1** [comment]
I think we're good to close this one.

Thanks again to everyone for ideas and feedback and the final product obviously!
